Three combined datasets; No feature selection

In [ ]:
import pandas as pd

file_path = 'Melbourne.csv'
df1 = pd.read_csv(file_path)

print("Dataset Information:")
print(df1.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47111 entries, 0 to 47110
Columns: 694 entries, last_update_date to 14
dtypes: float64(140), int64(553), object(1)
memory usage: 249.4+ MB
None


In [ ]:
# Load the CSV file
file_path = 'Santiago.csv'
df2 = pd.read_csv(file_path, error_bad_lines=False)

print("Dataset Information:")
print(df2.info())

<ipython-input-2-1f2bda5801a6>:3: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df2 = pd.read_csv(file_path, error_bad_lines=False)


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74576 entries, 0 to 74575
Data columns (total 84 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   last_update_date  74576 non-null  object 
 1   N_qubits          74576 non-null  int64  
 2   N_cx              74576 non-null  int64  
 3   N_measures        74576 non-null  int64  
 4   cx_0_1            74576 non-null  int64  
 5   cx_0_2            74576 non-null  int64  
 6   cx_0_3            74576 non-null  int64  
 7   cx_0_4            74576 non-null  int64  
 8   cx_1_0            74576 non-null  int64  
 9   cx_1_2            74576 non-null  int64  
 10  cx_1_3            74576 non-null  int64  
 11  cx_1_4            74576 non-null  int64  
 12  cx_2_0            74576 non-null  int64  
 13  cx_2_1            74576 non-null  int64  
 14  cx_2_3            74576 non-null  int64  
 15  cx_2_4            74576 non-null  int64  
 16  cx_3_0            7

In [ ]:
file_path = 'Athens.csv'
df3 = pd.read_csv(file_path, error_bad_lines=False)

print("Dataset Information:")
print(df3.info())

"""
Quantum Circuit Features:

last_update_date: Date of the last update for the dataset.
N_qubits: Number of qubits in the circuit.
N_cx: Number of CNOT (CX) gates in the circuit.
N_measures: Number of measurement operations in the circuit.
cx_0_1, cx_0_2, ..., cx_4_3: Number of CNOT gates between specific control and target qubits.
Columns '0', '1', '2', '3', '4': Mappings of circuit qubits onto processor qubits.
Quantum Processor Features:

edge_error_i_j: Error rate for the CNOT gate between qubits i and j.
edge_length_i_j: Execution time of a CNOT gate between qubits i and j.
T1_i, T2_i: Relaxation times for qubit i.
readout_error_i: Readout error for qubit i.
"""

<ipython-input-3-1283ac14a782>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df3 = pd.read_csv(file_path, error_bad_lines=False)


Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66747 entries, 0 to 66746
Data columns (total 84 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   last_update_date  66747 non-null  object 
 1   N_qubits          66747 non-null  int64  
 2   N_cx              66747 non-null  int64  
 3   N_measures        66747 non-null  int64  
 4   cx_0_1            66747 non-null  int64  
 5   cx_0_2            66747 non-null  int64  
 6   cx_0_3            66747 non-null  int64  
 7   cx_0_4            66747 non-null  int64  
 8   cx_1_0            66747 non-null  int64  
 9   cx_1_2            66747 non-null  int64  
 10  cx_1_3            66747 non-null  int64  
 11  cx_1_4            66747 non-null  int64  
 12  cx_2_0            66747 non-null  int64  
 13  cx_2_1            66747 non-null  int64  
 14  cx_2_3            66747 non-null  int64  
 15  cx_2_4            66747 non-null  int64  
 16  cx_3_0            6

"\nQuantum Circuit Features:\n\nlast_update_date: Date of the last update for the dataset.\nN_qubits: Number of qubits in the circuit.\nN_cx: Number of CNOT (CX) gates in the circuit.\nN_measures: Number of measurement operations in the circuit.\ncx_0_1, cx_0_2, ..., cx_4_3: Number of CNOT gates between specific control and target qubits.\nColumns '0', '1', '2', '3', '4': Mappings of circuit qubits onto processor qubits.\nQuantum Processor Features:\n\nedge_error_i_j: Error rate for the CNOT gate between qubits i and j.\nedge_length_i_j: Execution time of a CNOT gate between qubits i and j.\nT1_i, T2_i: Relaxation times for qubit i.\nreadout_error_i: Readout error for qubit i.\n"

In [ ]:
import pandas as pd

df = pd.concat([df2, df3], ignore_index=True)

df.head()

last_update_date  N_qubits  N_cx  N_measures  cx_0_1  cx_0_2  \
0  2020-10-10 07:17:41+02:00         4     8           4       2       0   
1  2020-08-10 06:48:41+02:00         4    11           4       2       0   
2  2020-09-22 07:29:45+02:00         3     1           3       0       1   
3  2020-08-19 07:22:12+02:00         2     2           2       2       0   
4  2020-09-13 07:23:19+02:00         4    10           4       0       1   

   cx_0_3  cx_0_4  cx_1_0  cx_1_2  ...        T2_3  readout_error_3  \
0       0       0       2       0  ...   63.606871           0.1042   
1       2       0       3       0  ...  142.586119           0.0220   
2       0       0       0       0  ...   79.593039           0.0112   
3       0       0       0       0  ...  118.551406           0.0124   
4       0       0       2       0  ...  100.517598           0.0120   

         T1_4        T2_4  readout_error_4    0    1    2    3    4  
0  121.557123  140.043883           0.0099  NaN  0.0  1.0  2.0  3.0  
1  153.544861  161.149771           0.0220  2.0  0.0  1.0  NaN  3.0  
2  138.187089  165.342556           0.0070  1.0  NaN  0.0  2.0  NaN  
3  118.631332  136.422589           0.0283  NaN  0.0  1.0  NaN  NaN  
4  114.518615  120.795876           0.0085  NaN  0.0  1.0  2.0  3.0  

[5 rows x 84 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141323 entries, 0 to 141322
Data columns (total 84 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   last_update_date  141323 non-null  object 
 1   N_qubits          141323 non-null  int64  
 2   N_cx              141323 non-null  int64  
 3   N_measures        141323 non-null  int64  
 4   cx_0_1            141323 non-null  int64  
 5   cx_0_2            141323 non-null  int64  
 6   cx_0_3            141323 non-null  int64  
 7   cx_0_4            141323 non-null  int64  
 8   cx_1_0            141323 non-null  int64  
 9   cx_1_2            141323 non-null  int64  
 10  cx_1_3            141323 non-null  int64  
 11  cx_1_4            141323 non-null  int64  
 12  cx_2_0            141323 non-null  int64  
 13  cx_2_1            141323 non-null  int64  
 14  cx_2_3            141323 non-null  int64  
 15  cx_2_4            141323 non-null  int64  
 16  cx_3_0            14

In [ ]:
# Print missing values
sorted_missing_values = df.isnull().sum().sort_values(ascending=False)
print("\nMissing Values (Sorted in Descending Order):")
print(sorted_missing_values)

# Calculate the percentage of rows with 0 null values
rows_with_zero_nulls = df[df.isnull().sum(axis=1) == 0]
percentage_zero_nulls = len(rows_with_zero_nulls) / len(df) * 100

print("\nPercentage of Rows with 0 Null Values: {:.2f}%".format(percentage_zero_nulls))


Missing Values (Sorted in Descending Order):
4                  55021
0                  31870
3                  30991
1                  12837
2                   9323
                   ...  
edge_error_0_2         0
edge_length_0_1        0
edge_error_0_1         0
cx_4_3                 0
edge_error_2_1         0
Length: 84, dtype: int64

Percentage of Rows with 0 Null Values: 39.43%


In [ ]:
df = df.drop(['last_update_date', 'N_measures'], axis=1)

In [ ]:
df.head()

N_qubits  N_cx  cx_0_1  cx_0_2  cx_0_3  cx_0_4  cx_1_0  cx_1_2  cx_1_3  \
0         4     8       2       0       0       0       2       0       0   
1         4    11       2       0       2       0       3       0       2   
2         3     1       0       1       0       0       0       0       0   
3         2     2       2       0       0       0       0       0       0   
4         4    10       0       1       0       0       2       0       1   

   cx_1_4  ...        T2_3  readout_error_3        T1_4        T2_4  \
0       0  ...   63.606871           0.1042  121.557123  140.043883   
1       0  ...  142.586119           0.0220  153.544861  161.149771   
2       0  ...   79.593039           0.0112  138.187089  165.342556   
3       0  ...  118.551406           0.0124  118.631332  136.422589   
4       0  ...  100.517598           0.0120  114.518615  120.795876   

   readout_error_4    0    1    2    3    4  
0           0.0099  NaN  0.0  1.0  2.0  3.0  
1           0.0220  2.0  0.0  1.0  NaN  3.0  
2           0.0070  1.0  NaN  0.0  2.0  NaN  
3           0.0283  NaN  0.0  1.0  NaN  NaN  
4           0.0085  NaN  0.0  1.0  2.0  3.0  

[5 rows x 82 columns]

In [ ]:
import pandas as pd
from sklearn.decomposition import PCA
import numpy as np

columns_to_fill_mean = df.columns.difference(['0', '1', '2', '3', '4'])

# Fill missing values with mean for selected columns
df[columns_to_fill_mean] = df[columns_to_fill_mean].fillna(df[columns_to_fill_mean].mean())

In [ ]:
columns_for_pca = [col for col in df.columns if col not in ['0', '1', '2', '3', '4']]
pca = PCA(n_components=10)
df_pca = pd.DataFrame(pca.fit_transform(df[columns_for_pca]), columns=[f'pca_{i}' for i in range(1, 11)])
df = pd.concat([df, df_pca], axis=1)

"""
df['interaction_term_2'] = df['T1_0'] + df['T2_0']
"""

"\ndf['interaction_term_2'] = df['T1_0'] + df['T2_0']\n"

In [ ]:
print(df.columns)

Index(['N_qubits', 'N_cx', 'cx_0_1', 'cx_0_2', 'cx_0_3', 'cx_0_4', 'cx_1_0',
       'cx_1_2', 'cx_1_3', 'cx_1_4', 'cx_2_0', 'cx_2_1', 'cx_2_3', 'cx_2_4',
       'cx_3_0', 'cx_3_1', 'cx_3_2', 'cx_3_4', 'cx_4_0', 'cx_4_1', 'cx_4_2',
       'cx_4_3', 'edge_error_0_1', 'edge_length_0_1', 'edge_error_0_2',
       'edge_length_0_2', 'edge_error_0_3', 'edge_length_0_3',
       'edge_error_0_4', 'edge_length_0_4', 'edge_error_1_0',
       'edge_length_1_0', 'edge_error_1_2', 'edge_length_1_2',
       'edge_error_1_3', 'edge_length_1_3', 'edge_error_1_4',
       'edge_length_1_4', 'edge_error_2_0', 'edge_length_2_0',
       'edge_error_2_1', 'edge_length_2_1', 'edge_error_2_3',
       'edge_length_2_3', 'edge_error_2_4', 'edge_length_2_4',
       'edge_error_3_0', 'edge_length_3_0', 'edge_error_3_1',
       'edge_length_3_1', 'edge_error_3_2', 'edge_length_3_2',
       'edge_error_3_4', 'edge_length_3_4', 'edge_error_4_0',
       'edge_length_4_0', 'edge_error_4_1', 'edge_length_4_1',
       'e

In [ ]:
df.head()

N_qubits  N_cx  cx_0_1  cx_0_2  cx_0_3  cx_0_4  cx_1_0  cx_1_2  cx_1_3  \
0         4     8       2       0       0       0       2       0       0   
1         4    11       2       0       2       0       3       0       2   
2         3     1       0       1       0       0       0       0       0   
3         2     2       2       0       0       0       0       0       0   
4         4    10       0       1       0       0       2       0       1   

   cx_1_4  ...       pca_1      pca_2       pca_3      pca_4      pca_5  \
0       0  ...  278.114830 -46.807734   -5.301100 -57.167985  -5.880393   
1       0  ...  322.640695  -6.995388   70.318667  15.395350 -34.639555   
2       0  ...  268.445015 -56.825469 -105.810030  30.513946 -49.990147   
3       0  ...  298.944153 -27.772347    4.688325  22.443717  -1.962218   
4       0  ...  283.991763 -41.334102  -43.065936  23.896578  13.534869   

       pca_6      pca_7      pca_8      pca_9    pca_10  
0 -40.232662  32.196324  -3.547475 -25.339084  2.778431  
1  12.164122 -22.082072 -16.602384  28.004119 -3.484511  
2 -14.762628  -2.383625  10.827274 -18.591304  9.984901  
3   8.600954 -12.384214  -4.378186  19.820021 -4.067319  
4   7.177964  -4.650486  14.051320   2.005281  4.581910  

[5 rows x 92 columns]

In [ ]:
correlation_matrix = df.corr().abs()
upper_tri = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(np.bool))
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > 0.8)]
print(to_drop)
df = df.drop(to_drop, axis=1)

['edge_error_1_0', 'edge_length_1_0', 'edge_length_1_2', 'edge_error_2_1', 'edge_length_2_1', 'edge_error_3_2', 'edge_length_3_2', 'edge_error_4_3', 'edge_length_4_3', 'T2_0', 'pca_1', 'pca_2', 'pca_5']


<ipython-input-13-e6e0533d7db1>:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  upper_tri = correlation_matrix.where(np.triu(np.ones(correlation_matrix.shape), k=1).astype(np.bool))


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

df[['0', '1', '2', '3', '4']] = df[['0', '1', '2', '3', '4']].fillna(-1)

X = df.drop(['0', '1', '2', '3', '4'], axis=1)
y = df[['0', '1', '2', '3', '4']].astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

dt_classifiers = {}

# Train a separate Decision Tree classifier for each label
for label in y.columns:
    dt_classifier = DecisionTreeClassifier(random_state=42)
    dt_classifier.fit(X_train_scaled, y_train[label])
    dt_classifiers[label] = dt_classifier

X_test_scaled = scaler.transform(X_test)

# Predict for each label using the corresponding Decision Tree classifier
dt_predictions = pd.DataFrame()

for label, dt_classifier in dt_classifiers.items():
    dt_predictions[label] = dt_classifier.predict(X_test_scaled)

# Evaluate the performance for each label
for label in y.columns:
    accuracy = accuracy_score(y_test[label], dt_predictions[label])
    print(f"Accuracy for label {label}: {accuracy:.4f}")

dt_accuracies = [accuracy_score(y_test[col], dt_predictions[col]) for col in y_test.columns]
dt_avg_accuracy = sum(dt_accuracies) / len(dt_accuracies)
print("Decision Trees Average Accuracy: {:.2f}".format(dt_avg_accuracy))

Accuracy for label 0: 0.3520
Accuracy for label 1: 0.3543
Accuracy for label 2: 0.3384
Accuracy for label 3: 0.3885
Accuracy for label 4: 0.4600
Decision Trees Average Accuracy: 0.38


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifiers = {}

for label in y.columns:
    knn_classifier = KNeighborsClassifier(n_neighbors=5)
    knn_classifier.fit(X_train_scaled, y_train[label])
    knn_classifiers[label] = knn_classifier

knn_predictions = pd.DataFrame()

for label, knn_classifier in knn_classifiers.items():
    knn_predictions[label] = knn_classifier.predict(X_test_scaled)

for label in y.columns:
    accuracy = accuracy_score(y_test[label], knn_predictions[label])
    print(f"Accuracy for label {label} (KNN): {accuracy:.4f}")

knn_accuracies = [accuracy_score(y_test[col], knn_predictions[col]) for col in y_test.columns]
knn_avg_accuracy = sum(knn_accuracies) / len(knn_accuracies)
print("KNN Average Accuracy: {:.4f}".format(knn_avg_accuracy))


Accuracy for label 0 (KNN): 0.3575
Accuracy for label 1 (KNN): 0.3632
Accuracy for label 2 (KNN): 0.3534
Accuracy for label 3 (KNN): 0.3992
Accuracy for label 4 (KNN): 0.4962
KNN Average Accuracy: 0.3939


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

rf_classifiers = {}
xgb_classifiers = {}

for label in y.columns:
    rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
    rf_classifier.fit(X_train_scaled, y_train[label])
    rf_classifiers[label] = rf_classifier

rf_predictions = pd.DataFrame()

for label, rf_classifier in rf_classifiers.items():
    rf_predictions[label] = rf_classifier.predict(X_test_scaled)

for label in y.columns:
    accuracy = accuracy_score(y_test[label], rf_predictions[label])
    print(f"Accuracy for label {label} (Random Forest): {accuracy:.4f}")

rf_accuracies = [accuracy_score(y_test[col], rf_predictions[col]) for col in y_test.columns]
rf_avg_accuracy = sum(rf_accuracies) / len(rf_accuracies)
print("Random Forest Average Accuracy: {:.4f}".format(rf_avg_accuracy))


Accuracy for label 0 (Random Forest): 0.4229
Accuracy for label 1 (Random Forest): 0.4226
Accuracy for label 2 (Random Forest): 0.4023
Accuracy for label 3 (Random Forest): 0.4491
Accuracy for label 4 (Random Forest): 0.5390
Random Forest Average Accuracy: 0.4472


In [ ]:
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier

label_encoder = LabelEncoder()

xgb_classifiers = {}
for label in y.columns:
    label_encoder.fit(y_train[label])
    y_train_encoded = label_encoder.transform(y_train[label])
    print(y_train_encoded)

    xgb_classifier = XGBClassifier(learning_rate=0.1, n_estimators=100, random_state=42)
    xgb_classifier.fit(X_train_scaled, y_train_encoded)
    xgb_classifiers[label] = xgb_classifier

xgb_predictions = pd.DataFrame()

for label, xgb_classifier in xgb_classifiers.items():
    xgb_predictions[label] = label_encoder.inverse_transform(xgb_classifier.predict(X_test_scaled))

xgb_accuracies = [accuracy_score(y_test[col], xgb_predictions[col]) for col in y_test.columns]
xgb_avg_accuracy = sum(xgb_accuracies) / len(xgb_accuracies)
print("XGBoost Average Accuracy: {:.4f}".format(xgb_avg_accuracy))

[4 4 0 ... 4 5 3]
[3 3 0 ... 3 3 2]
[1 5 1 ... 2 4 1]
[2 1 2 ... 1 1 0]
[0 2 0 ... 0 2 0]
XGBoost Average Accuracy: 0.4957


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.multioutput import MultiOutputClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer

from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],)),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(y_train.shape[1], activation='sigmoid')
])

model.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=50, batch_size=64, validation_split=0.2)

cnn_predictions = model.predict(X_test)
cnn_accuracies = [accuracy_score(y_test[col], (cnn_predictions[:, idx] > 0.5).astype(int)) for idx, col in enumerate(y_test.columns)]
cnn_avg_accuracy = sum(cnn_accuracies) / len(cnn_accuracies)
print("CNN Average Accuracy: {:.4f}".format(cnn_avg_accuracy))

Epoch 1/50
1414/1414 [==============================] - 8s 5ms/step - loss: -271568.0625 - accuracy: 0.2571 - val_loss: -1097035.3750 - val_accuracy: 0.2403
Epoch 2/50
1414/1414 [==============================] - 6s 4ms/step - loss: -3605652.7500 - accuracy: 0.2946 - val_loss: -7271233.5000 - val_accuracy: 0.3494
Epoch 3/50
1414/1414 [==============================] - 7s 5ms/step - loss: -13147626.0000 - accuracy: 0.3253 - val_loss: -20632444.0000 - val_accuracy: 0.3494
Epoch 4/50
1414/1414 [==============================] - 6s 4ms/step - loss: -30304242.0000 - accuracy: 0.3378 - val_loss: -42245992.0000 - val_accuracy: 0.3494
Epoch 5/50
1414/1414 [==============================] - 7s 5ms/step - loss: -56419964.0000 - accuracy: 0.3450 - val_loss: -73633560.0000 - val_accuracy: 0.3494
Epoch 6/50
1414/1414 [==============================] - 6s 4ms/step - loss: -92748376.0000 - accuracy: 0.3431 - val_loss: -115781872.0000 - val_accuracy: 0.3494
Epoch 7/50
1414/1414 [======================